### PR TITLE
fix: Remove the playlist UI when the player is disposed.

### LINKED ISSUE #78: Dispose of the playlist element when the player is disposed
## Description
If you have a player with a playlist-ui, when the player is disposed it is taken out of the DOM but the playlist UI stays. Instead, it should be removed as well when the player is disposed.

## Steps to reproduce
1. create a new player
2. initialize the playlist-ui
3. call `player.dispose()`

### Expected
The player and the playlist-ui are gone from the DOM

### Actual
The player is gone from the DOM but the playlist-ui is still there.

There's work to add an event for when `player.reset()` is called, that should probably be handled as well and the playlist be cleared.

### PR DESCRIPTION
**Pull request by misteroneill**
Fixes #78 

* Remove the playlist UI when the player is disposed.
* Remove the `playlistMenu` component reference from the player when the `playlistMenu` is disposed.

## Requirements Checklist
- [x] Feature implemented / Bug fixed
- [x] If necessary, more likely in a feature request than a bug fix
  - [x] Unit Tests updated or fixed
- [ ] Reviewed by Two Core Contributors

### CODE REVIEW

File: src/plugin.js [hunk 1]
```diff
@@ -232,19 +232,27 @@ class PlaylistMenu extends Component {
       this.addClass('vjs-mouse');
     }
 
-    player.on(['loadstart', 'playlistchange', 'playlistsorted'], (event) => {
+    this.on(player, ['loadstart', 'playlistchange', 'playlistsorted'], (event) => {
```
Comment (misteroneill) [inline src/plugin.js]: This means we properly stop listening to player events if the component is disposed.

File: src/plugin.js [hunk 2]
```diff
@@ -232,19 +232,27 @@ class PlaylistMenu extends Component {
...
+    this.on(player, 'adend', () => {
       this.removeClass('vjs-ad-playing');
     });
+
+    this.on('dispose', () => {
+      player.playlistMenu = null;
+    });
+
+    this.on(player, 'dispose', () => {
+      this.dispose();
```
Comment (gkatsev) [inline src/plugin.js]: looks like PlaylistMenuItems are created and added manually rather than using the video.js component API, so, we need to dispose them manually as well
https://github.com/brightcove/videojs-playlist-ui/blob/767b7ac4d3f5986f07a9b49f43c3c56202fa754c/src/plugin.js#L272-L279

Comment (misteroneill) [reply src/plugin.js]: Bahhhhhhhh.
